spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fruits?createDatabaseIfNotExist=true&&UseSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
